# -*- coding: utf-8 -*-
#Text_list.py

def text_get():
    txt = {
               "0":["HA","JI","ME","KA","RA"],
               "1":["YA","ME","RU"],
               "2":["SO","NO","KU","NI","DE","HA","TA","I","YO",
                          "U","WO","O","U","NO",],
               "3":["KE","SI","NN","TO","KA","NN","GA","E",","],
               "4":["HI","GA","KA","GE","RU","KO","TO","WO","O",
                          "U","NO","TI","KA","RA","NO"],
               "5":["KA","GE","RI","TO","KA","NN","GA","E","TE",
                          "I","TA"],
               "6":["SE","-","BU","SI","MA","SI","TA"],
               "7":["SE","-","BU","NI","SI","tu","PA","I","SI","MA","SI","TA"],
               "8":["RO","-","DO","SI","MA","SI","TA"],
               "9":["RO","-","DO","NI","SI","tu","PA","I","SI","MA","SI","TA"],
               "10":["TU","DU","KI","KA","RA"],
               "11":["HI","NO","KA","GE","RI","WO","MI","TO","ME","TA"],
               "12":["DA","I","SI","NN","KA","NN","HA","O","U","GO","RO","SI",
                     "NO",],
               "13":["KA","I","SI","WO","SE","NN","GE","NN","SI","TA"],
               "14":["O","U","WO","KO","RO","SI","TA","MO","NO","GA",],
               "15":["TU","GI","NO","O","U","TO","NA","RU",],
               "16":["NA","NO","KA","KA","NN","O","U","GA","I","KI","NO","BI",
                     "TA","RA",","],
               "17":["SO","NO","TI","KA","RA","HA","I","MA","DA","KE","NN",
                     "ZA","I","TO","SI",","],
               "18":["O","U","GO","RO","SI","HA","O","WA","RU",],
               "19":["GI","yo","KU","ZA","WO","NE","RA","U","HI","TO","RI",
                     "TO","SI","TE"],
               "20":["A","NA","TA","MO","KO","U","DO","U","WO","KA","I","SI",
                     "SI","TA",],
               "21":[".",".",".","KO","NO","GE","NN","SI","yo","U","GA",],
               "22":["NI","tu","SI","yo","KU",],
               "23":["TO","SI","TE","YO","NI","SI","RA","RE","RU","NO","HA",],
               "24":["MA","DA","SA","KI","NO","HA","NA","SI","DE",
                     "A","RU",".",".","."],
               "25":["A","NA","TA","GA","O","U","KI","yu","U","NI",],
               "26":["TA","DO","RI","TU","KU","TO"],
               "27":["SU","DE","NI","O","U","HA","SO","KO","NI","I","NA","KA",
                     "tu","TA"],
               "28":["YU","KU","TE","WO","HA","BA","MU","KI","SI","DA","NN",
                     "TI","yo","U","WO"],
               "29":["TA","O","SI","TA","A","NA","TA","HA"],
               "30":["O","U","NO","YU","KU","E","WO","O","U","KO","TO","WO"],
               "31":["KE","TU","I","SU","RU",".",".",".",],
               "32":["KE","I","SI","yo","U","NO","SA","I","DA","NN","NI","HA",
                     "I","RU",],
               "33":["NI","HA","O","U","NO","SO","tu","KI","NN","TA","TI",
                     "GA","MO","TU",],
               "34":["KA","GI","GA","HI","TU","YO","U","TO","NA","RU"],
               "35":["A","NA","TA","HA","SO","tu","KI","NN","NO","HI","TO",
                     "RI","DE","A","RU"],
               "36":["HA","KU","GI","NN","NO","KI","SI","WO","O","tu","TE",],
               "37":["HE","NN","KI","yo","U","NO","MU","RA","NI","TA","DO",
                     "RI","TU","I","TA"],
               "38":["O","U","NO","SO","tu","KI","NN","DE","A","RU",],
               "39":["MA","DO","U","I","NN","TI","yo","U","WO","O","tu","TE"],
               "40":[],
               "41":["A","NA","TA","HA","O","U","RI","TU","MA","DO","U","I",
                     "NN","NI",],
               "42":["TA","DO","RI","TU","I","TA"],
               "43":[],
               "44":["MA","DO","U","I","NN","NO","SA","I","SI","NN","BU",
                     "NI",],
               "45":["SU","SU","MI","KA","GI","WO","TE","NI","I","RE","NA",
                     "KE","RE","BA",],
               "46":["NA","RA","NA","I"],
               "50":["BU","KI","WO","KE","NN","NI","MO","TI","KA","E","TA"],
               "51":["BU","KI","WO","TU","E","NI","MO","TI","KA","E","TA"],
               "52":["BU","KI","WO","O","NO","NI","MO","TI","KA","E","TA"],
               "53":["BU","KI","WO","E","RA","NN","DE","KU","DA","SA","I"],
               "60":["O","U","NO","SO","tu","KI","NN","DE","A","RU",],
               "61":["MI","DO","RI","NO","KI","SI","WO","O","tu","TE"],
               "62":[],
               "63":["A","NA","TA","HA","HI","GA","SI","NO","MI","YA","KO",
                     "NI",],
               "64":["TA","DO","RI","TU","I","TA"],
               "65":[],
               "66":["KO","NO","I","KO","KU","NO","TI","WO","TA","NN","SA",
                     "KU","SI"],
               "67":["KA","GI","WO","TE","NI","I","RE","NA",
                     "KE","RE","BA","NA","RA","NA","I"],
               "68":[],
               "70":["A","NA","TA","HA","TU","I","NI","SU","BE","TE","NO"],
               "71":["KA","GI","WO","TE","NI","I","RE","TA",],
               "72":[],
               "73":["KE","I","SI","yo","U","NO","SA","I","DA","NN","NI"],
               "74":["SU","SU","MI",",",],
               "75":[],
               "76":["KO","NO","O","U","GO","RO","SI","WO","O","WA","RA",
                     "SE","RU"],
               "77":["TO","KI","GA","YA","tu","TE","KI","TA",],
               "78":[],               
               "79":[],               
               "80":[],               
               "81":[],               
               "100":["KA","GI","GA","A","I","TA",],
               "101":["KA","GI","GA","KA","KA","tu","TE","I","RU"],
               "102":["SI","KA","KE","GA","SA","DO","U","SI","TA"],
               "103":["DO","KU","RO","WO","HA","KA","I","SI","TA"],
               "104":["KU","DA","KA","RE","TA","DO","KU","RO",],
               "105":["NI","MU","KA","I","MA","SU",".",".","."],
               "105_0":["DO","KO","HE","I","KI","MA","SU","KA","?"],
               "105_1":["HE","NN","KI","yo","U","NO","MU","RA"],
               "105_2":["O","U","RI","TU","MA","DO","U","I","NN"],
               "105_3":["HI","GA","SI","NO","MI","YA","KO",],
               "105_4":["KE","I","SI","yo","U","NO","SA","I","DA","NN"],
               "105_6":["KI","yu","U","SI","GA","I","NO","MI","NA","TO"],
               "105_7":["SU","I","MO","NN","GA","A","I","TE","I","NA","I","!"],
               "106":["MA","MO","NO","NI","TI","yu","U","I"],
               "107":["KO","NO","SA","KI","MI","YA","KO","SE","I","MO","NN",],
               "108":["TA","TI","I","RI","KI","NN","SI",],
               "109":["KI","yu","U","SI","GA","I","TA","TI","I","RI","KI",
                      "NN","SI",],
               "110":["DA","I","NI","TI","KU","HU","NA","TU","KI","BA",],
               "111":["I","BA","RA","GA","MI","TI","WO","HU","SA","I","DE",
                      "I", "RU",],
               "112":["I","BA","RA","WO","YA","KI","HA","RA","tu","TA",],
               "113":["TA","I","MA","TU","WO","TE","NI","I","RE","TA"],
               "113_1":["BA","KU","YA","KU","WO","TE","NI","I","RE","TA"],
               "114":["NA","NI","MO","NA","I",],
               "115":["KA","GI","YO","NN","WO","TE","NI","I","RE","TA"],
               "116":["JI","yo","U","HO","U","SA","NN","WO","TE","NI","I",
                      "RE","TA"],
               "117":["SO","KO","MA","DE","DA",",","TA","BI","BI","TO","YO",],
               "118":["HE","I","KA","HA","SU","DE","NI","TA","BI","DA","TA",
                      "RE","TA"],
               "119":["I","KA","NI","KU","NI","NO","O","KI","TE","TO",
                      "HA","I","E",","],
               "120":["HE","I","KA","HA","KO","RO","SA","SE","NN"],
               "121":[".",".",".",".",".",".",".",".","."],
               "122":["KI","KO","U",",","SI","NN","DE","MO","RA","U",
                      "ZO","!",],
               "123":["KI","SI","DA","NN","TI","yo","U",],
               "124":["KI","TI","yo","U","HI","NN","WO","TE","NI","I","RE",
                      "TA"],
               "125":["O","U","GO","RO","SI","NO","TA","BI","BI","TO","KA"],
               "126":["GI","SI","KI","NI","SA","NN","KA","SI","TA",
                      "I","NA","RA"],
               "127":["O","U","KE","NO","ME","DA","RU","WO","MI","TU","KE",
                      "RU","KO","TO","JI","ya"],
               "128":["SE","I","ZE","I","TA","tu","SI","ya","DE","NA"],
               "129":["KO","NO","SA","KI","SI","NN","SE","I","TI","KU"],
               "130":["KO","NO","SA","KI","MU","RA","I","RI","GU","TI"],
               "131":["KE","I","SI","yo","U","NO","SA","I","DA","NN"],
               "132":["KA","GI","GO","WO","TE","NI","I","RE","TA",],
               "133":["KA","I","ZU","NO","TA","BA","WO","TE","NI","I","RE",
                      "TA"],
               "134":["I","MA","HA","DA","RE","MO","I","NA","I"],
               "135":["TO","BI","RA","WO","HI","RA","I","TA",],
               "136":["HA","KU","GI","NN","NO","KI","SI",],
               "137":["O","MO","tu","TA","YO","RI","SU","BA","YA","I","NA"],
               "138":["I","SO","I","DE","JI","NN","WO","SI","KE","!",],
               "139":["MU","KA","E","U","TU","ZO","!",],
               "140":["GA","NN","BA","NN","DE","HU","SA","GA","RE","TE","I",
                      "RU"],
               "141":["BA","KU","YA","KU","WO","TU","KA","tu","TA",],
               "142":["MU","RA","NI","HA","TI","KA","YO","RA","NA","I","HO",
                      "U","GA","I","I"],
               "143":["KI","SI","DA","NN","NI","ME","WO","TU","KE","RA","RE",
                      "RU","ZO"],
               "144":["MU","RA","BI","TO","HA","MI","NN","NA","HI","NA","NN",
                      "SI","TA"],
               "145":["NO","KO","tu","TE","I","RU","NO","HA","SO","NN","TI",
                      "yo","U","DA","KE"],
               "146":["YO","SO","MO","NO","GA","KO","KO","DE","NA","NI","WO",
                      "SI","TE","I","RU","?",],
               "147":["KO","U","KI","SI","NN","NE","KO","WO","MO","KO","RO",
                      "SU","TO","I","U","ZO"],
               "148":["WA","RU","I","KO","TO","HA","I","WA","NA","I",],
               "149":["HA","YA","I","TO","KO","O","KA","E","RI",".",".",
                      ".",],
               "150":["I","MA","DA",",","KA","KA","RE","tu","!","!",],
               "151":["TA","TI","I","RU","SA","I","HA","WA","NN","SI","yo",
                      "U","WO",],
               "151_1":["TU","KE","RU","KO","TO"],
               "152":["BA","KU","YA","KU","A","RI",",","KI","KE","NN",],
               "153":["MU","RA","NO","HI","MI","TU","WO","SI","tu","TA",
                      "MO","NO","WO"],
               "154":["I","KA","SI","TE","O","KU","WA","KE","NI","HA",
                      "I","KA","NN"],
               "155":["SO","NN","TI","yo","U",],
               "156":["TO","KI","NO","KE","NN","KI","yu","U","JI","yo"],
               "157":["MA","A","TA","RA","SI","I","HA","KA","DA",],
               "200":[".",".",".",".",".",".",],
               "201":["KO","NN","NI","TI","HA",],
               "202":["SA","I","KI","NN","MA","MO","NO","GA","O","O",
                      "KU","NA","tu","TA",],
               "203":["O","U","SA","MA","WO","SI","BA","RA","KU","MI",
                      "TE","I","NA","I","NA",],
               "204":["MI","YA","KO","NO","TI","KA","NI","TU","U","RO",
                      "GA","A","RU","RA","SI","I",],
               "205":["KO","NN","NI","TI","HA",],
               "206":["KO","NN","NI","TI","HA",],
               "207":["MI","NA","TO","GA","HU","U","SA","SA","RE","TE",
                      "KO","MA","tu","TE","MA","SU",],
               "208":["KO","NN","NI","TI","HA",],
               "209":["KO","NN","NI","TI","HA",],
               "210":["MI","NA","TO","NO","E","I","HE","I","HA","I",
                      "NE","MU","RI","BA","KA","RI",],
               "211":["KO","NN","NI","TI","HA",],
               "212":["KO","NN","NI","TI","HA",],
               "213":["KO","KO","HA","SI","NN","SE","I","TI","KU","DE",
                      "SU",],
               "214":["NA","NI","KA","GO","YO","U","DE","SU","KA","?"],
               "215":["KO","NN","NI","TI","HA",],
               "216":["DA","I","SI","NN","KA","NN","SA","MA","NI","A","U",
                      "NO","NA","RA"],
               "217":["SI","NN","DE","NN","NI","MU","KA","tu","TE","KU","DA",
                      "SA","I"],
               "218":["KO","NO","MI","TI","NO","TU","KI","A","TA","RI","GA"],
               "219":["DA","I","SI","NN","KA","NN","SA","MA","NO","O","TA",
                      "KU","DE","SU"],
               "220":["YO","KU","ZO","MA","I","tu","TA",",","TA","BI","BI",
                      "TO","YO"],
               "221":["KO","KU","O","U","HA","ME","I","KU","NN","DA","GA"],
               "222":["WA","SI","MO","KU","NI","NO","O","KI","TE","NI",
                      "HA","SA","KA","RA","E","NN"],
               "223":["KA","RE","WO","RA","KU","NI","SI","TE",
                      "YA","tu","TE","KU","RE"],
               "224":["O","U","HA","SA","I","DA",
                      "NN","NI","MU","KA","tu","TA","YO","U","DA"],
               "225":["KA","GI","HA","SO","tu","KI","NN","TA","TI","GA","MO",
                      "tu","TE","I","RU",],
               "226":["O","U","RI","TU","MA","DO","U","I","NN",],
               "227":["DO","A","SE","I","GI","yo","SI","TU",],
               "228":["JI","tu","KE","NN","TO","U","I","RI","GU","TI",],
               "229":["KI","NN","KI","yu","U","RE","NN","RA","KU",],
               "230":["KO","TI","RA","HA","TO","U","TI","yo","KU","SI",
                      "yo","U","KO","U"],
               "231":["SI","NN","NI","yu","U","SI","ya","WO","KE","NN",
                      "TI","SI","TA"],
               "232":["RI","NN","SE","NN","TA","I","SE","I","NI",
                      "HA","I","RE"],
               "233":["I","JI","yo","U",],
               "234":["TI","KA","I","tu","KA","I"],
               "235":["DA","I","I","TI","TI","yo","U","SE","I","SI","TU"],
               "236":["DA","I","NI","TI","yo","U","SE","I","SI","TU"],
               "237":["DA","I","SA","NN","TI","yo","U","SE","I","SI","TU"],
               "238":["KA","GI","GA","A","I","TA",],
               "239":["A","NN","SI","yo","U","BA","NN","GO","U","GA","TI",
                      "GA","I","MA","SU"],
               "240":["A","NN","SI","yo","U","BA","NN","GO","U","NI","yu",
                      "U","RI","yo","KU"],
               "241":["TO","SI","yo","SI","TU",],
               "242":["TI","KA","NI","KA","I"],
               "243":["TI","KA","SA","NN","KA","I"],
               "244":["DA","I","YO","NN","TI","yo","U","SE","I","SI","TU"],
               "245":["DA","I","RO","KU","TI","yo","U","SE","I","SI","TU"],
               "250":["HE","NN","KI","yo","U","NO","MU","RA","DE","HA"],
               "2501":["NA","ZO","NO","I","BU","TU","GA","MI","TU","KA",
                       "tu","TA","RA","SI","I"],
               "251":["MA","DO","U","I","NN","NO","SA","I","SI","NN",
                      "BU","DE","HA"],
               "2511":["GO","KU","HI","KE","NN","KI","yu","U","GA","SU",
                       "SU","NN","DE","I","RU"],
               "252":["HI","GA","SI","NO","MI","YA","KO","NI","HA"],
               "2521":["MA","MO","NO","NO","SI","NN","ZO","U","GA","MA",
                       "TU","RA","RE","TE","I","RU"],
               "253":["KA","KU","NI","NN","SI","TA","HO","U","GA","I","I",
                      "KA","MO","SI","RE","NN","NA"],
               "254":["SO","NO","KA","GI","HA",",",",",",",],               
               "255":["SO","U","KA",",","O","WA","tu","TA","YO","U","DA","NA"],
               "256":["SI","NN","DE","NN","NO","TI","KA","NI","I",
                      "KI","TA","MA","E"],
               "257":["SO","KO","DE","SU","BE","TE","GA","O","WA","RU",",",
                      ",",","],
               "300":["MI","YA","KO","NO","E","I","HE","I",],
               "301":["MI","YA","KO","NO","JI","yu","U","NI","NN"],
               "302":["RO","U","JI","NN"],
               "303":["RO","U","BA",],
               "304":["MU","RA","BI","TO"],
               "305":["JI","yu","U","NI","NN"],
               "306":["DA","I","SI","NN","KA","NN"],
               "307":["MA","DO","U","I","NN","SI","yo","U","KO","U"],
               "308":["MA","DO","U","I","NN","TI","yo","U",],
               "309":["O","U","GO","RO","SI","NO","TA","BI","BI","TO","KA"],
               "310":["NA","NI","MO","SI","RA","NU","O","RO","KA","MO","NO",
                      "ME"],
               "311":["MU","KU","NA","MA","MA","SI","NU","GA","I","I"],
               "312":["MA","RI","yo","KU","RA","NN","TA","NN","WO","TE","NI",
                      "I","RE","TA"],
               "313":["KI","TI","yo","U","HI","NN","SA","NN","WO",
                      "TE","NI","I","RE","TA"],
               "400":["GA","NN","YA","KU","WO","TE","NI","I","RE","TA"],               
               "401":["HI","RA","KA","NA","I",],       
               "402":["HI","GA","SI","NO","MI","YA","KO"],       
               "403":["KO","NO","SA","KI","TA","I","KI","yo","KU","DE","NN"],       
               "404":["SO","U","KO","SI","yu","U","RI","TI","yu","U",],       
               "405":["TO","BI","RA","GA","HI","RA","I","TA",],       
               "406":["KO","KO","MA","DE","KI","TA","KA",],       
               "407":["GO","KU","RO","U","NA","KO","TO","DA",],       
               "408":["KI","SA","MA","NO","SI","yu","U","NE","NN","NI"],       
               "409":["KE","I","I","WO","SI","ME","SI",],       
               "410":["HI","GA","SI","NO","MI","YA","KO","NO","RI","yu","U",
                      "GI","DE"],       
               "411":["KE","SI","TE","YA","RO","U",],       
               "412":["MI","DO","RI","NO","KI","SI",],       
               "413":["KI","TI","yo","U","HI","NN","YO","NN","WO",
                      "TE","NI","I","RE","TA"],
               "414":["DA","I","KI","TI",],  
               "415":["TI","yu","U","KI","TI",],  
               "416":["KI","TI",],  
               "417":["KI","yo","U",],  
               "418":["DA","I","KI","yo","U",],  
               "419":["O","MI","KU","JI",],  
               "420":["KO","KU","O","U",],  
               "421":["YO","KU","ZO","KO","KO","MA","DE",
                      "TA","DO","RI","TU","I","TA"],  
               "422":["O","U","GO","RO","SI","NO","TA","BI","BI","TO","YO"],  
               "423":["KO","KO","HA","KE","I","SI","YO","U","NO","SA","I",
                      "DA","NN"],  
               "424":["O","U","GO","RO","SI","NO","SI","yu","U","TI","ya",
                      "KU","TE","NN"],  
               "425":["KI","KO","U","GA","GI","yo","KU","ZA","NI",],  
               "426":["HU","SA","WA","SI","I","KA","DO","U","KA",],  
               "427":["KO","NO","TE","DE","TA","SI","KA","ME","SA","SE","TE",
                      "MO","RA","U"],  
               "428":["DA","I","ZA","WO","SE","tu","TI","SI","TA",],                 
               "4281":["NA","ZO","NO","KU","BO","MI","GA","A","RU",],   
               "429":["SU","I","SI","yo","U","WO","SE","tu","TI","SI","TA",],                 
               "4291":["MA","RU","I","KU","BO","MI","GA","A","RU",],   
               "430":["KI","BA","KO","WO","SE","tu","TI","SI","TA",],                
               "4301":["TI","I","SA","NA","SI","KA","KU","I",
                       "KU","BO","MI","GA","A","RU",],   
               "431":["KO","I","NN","WO","SE","tu","TI","SI","TA",],    
               "4311":["TI","I","SA","NA","MA","RU","I",
                       "KU","BO","MI","GA","A","RU",],        
               "500":["YO","U","KO","SO",",","TA","BI","BI","TO","YO"],                       
               "501":["O","U","GO","RO","SI","NO","YA","KU","ME",],           
               "502":["GO","KU","RO","U","DA","tu","TA"],                       
               "503":["SI","KA","SI",",","GI","yo","KU","ZA","WO","E","RA",
                      "BA","ZU"],                       
               "504":["KO","KO","HE","KI","TA","TO","I","U","KO","TO","HA"],                       
               "505":["O","NO","RE","NO","HO","NN","TO","U","NO","YA","KU",
                      "WA","RI","NI"],                       
               "506":["KI","GA","TU","I","TA","YO","U","DA","NA"],                       
               "507":["KI","KO","U","GA","A","TU","ME","TE","KU","RE","TA",
                      "NO","HA"],                       
               "508":["U","SI","NA","WA","RE","TA","U","RO","BO","RO","SU",
                      "NO"],                       
               "509":["TI","KA","RA","NO","KA","KE","RA","DA"],                       
               "510":["WA","RE","WA","RE","HA","SO","RE","WO"],                       
               "511":["ZU","tu","TO","SA","GA","SI","TE","I","TA",".",".","."],   
               "512":["MO","KU","TE","KI","HA","TA","DA","HI","TO","TU"],   
               "513":[],   
               "514":["JI","KA","NN","NO","NA","GA","RE","NO","HA","KA","I",
                      "DA"],   
               "515":["U","RO","BO","RO","SU","HA","E","I","E","NN",
                      "NO","SI","NN","BO","RU"],   
               "516":["SO","NO","TI","KA","RA","HA","JI","KA","NN","JI","KU",
                      "HE","NO"],   
               "517":["KA","NN","SI","yo","U","WO","KA","NO","U","NI","SU",
                      "RU"],   
               "518":["JI","KA","NN","NO","NA","GA","RE","GA","HA","KA","I",
                      "SA","RE","RE","BA"],   
               "519":["SO","KO","NI","HA","KA","KO","MO","NA","KE","RE","BA"],   
               "520":["MI","RA","I","MO","NA","I"],   
               "521":["KO","U","HU","KU","NA","GE","NN","ZA","I","GA","TU",
                      "DU","KU","NO","MI"],                  
               "522":["SO","RE","HA","MI","RA","I","HE","NO","HU","A","NN",
                      "KA","RA","NO",","],                  
               "523":["KI","yo","U","HU","KA","RA","NO","KA","I","HO",
                      "U","DA"],                  
               "524":["MI","TA","MA","E",",","KO","NO","KE","tu","SI","yo",
                      "U","GA"],                  
               "525":["JI","KA","NN","NO","NA","GA","RE","SO","NO","MO",
                      "NO","DA"],                  
               "526":["KI","KO","U","NO","TE","DE","KU","DA","KU","NO","DA"],                  
               "527":["O","U","GO","RO","SI","WO","NA","SI","TO","GE",
                      "TA","KI","KO","U","HA",],                        
               "528":["SO","NO","TI","KA","RA","GA","A","RU"],                        
               "529":["O","RO","KA","MO","NO","ME",],                        
               "530":["SI","TU","BO","U","SI","TA","ZO",],                        
               "531":["KE","tu","KI","yo","KU","HA",",","WA","TA","SI","GA"],                        
               "532":["YA","RU","SI","KA","NA","I","TO","I","U","KO",
                      "TO","KA",",",",",","],                        
               "999":["KO","KO","MA","DE","SI","KA","DE","KI","TE","MA",
                      "SE","NN"],
               "999_1":["GO","ME","NN","NA","SA","I","!","!",],
               "1000":["KI","yu","U","SI","GA","I","NI","TU","I","TE"],
               "1001":["KI","yu","U","SI","GA","I","HA",],
               "1002":["TO","KI","NO","KE","NN","KI","yu","U","JI","yo","NO",
                       "JI","KO","GA",],
               "1003":["MO","TO","DE","HE","I","SA","SA",
                       "RE","TA"],
               "1004":["KI","yu","U","JI","yo","HA","NN","GA","GE","NN","TI",
                       "NI","TU","I","TA",],
               "1005":["TO","KI","NI","HA",",","JI","yu","U","MI","NN","HA",],
               "1006":["KI","yu","U","SO","KU","NI","RO","U","KA","GA","SU",
                       "SU","MI",],
               "1007":["SU","DE","NI","RO","U","SU","I","DE","SI","BO","U",
                       "SI","TE","I","RU",],
               "1008":["MO","NO","MO","I","TA","TO","I","U"],
               "1009":["HE","NN","KI","yo","U","NO","MU","RA","NI","TU","I",
                       "TE"],
               "1010":["HE","NN","KI","yo","U","NO","MU","RA","HA","TO","U",
                       "DA","I","NO"],
               "1011":["O","U","NO","SI","yu","tu","SI","NN","TI","DE",",",
                       "MI","DO","RI","NI",],
               "1012":["KA","KO","MA","RE","TA","NO","DO",
                       "KA","NA","MU","RA","DE","A","RU"],
               "1013":["MU","RA","NO","KI","TA","NI","HA",],
               "1014":["KO","DA","I","NO","I","SE","KI","GA","A","RI",],
               "1015":["BU","NN","KA","ZA","I","HO","GO","HA","NN","GA","TI",
                       "yo","U","SA","WO"],
               "1016":["O","KO","NA","tu","TE","I","RU"],
               "1017":[],
               "1018":["O","U","RI","TU","MA","DO","U","I","NN","NI","TU","I",
                       "TE"],
               "1019":["O","U","RI","TU","MA","DO","U","I","NN","HA",],
               "1020":["TO","KI","NO","KE","NN","KI","yu","U","JI","yo","WO",
                       "HI","KI","TU","GU"],
               "1021":["KA","TA","TI","DE","SI","NN","SE","TU","SA","RE","TA"],
               "1022":["MA","DO","U","I","NN","TI","yo","U","WO","TO","tu",
                       "PU","NI"],
               "1023":["GU","NN","TA","I","NO","YO","U","NA","KI","RI","TU",
                       "GA","A","RI"],
               "1024":["KI","SI","DA","NN","KA","RA","DO","KU","RI","TU","SI",
                       "TA",],
               "1025":["GU","NN","JI","RI","yo","KU","WO","MO","TU"],
               "1026":[],
               "1027":["HI","GA","SI","NO","MI","YA","KO","NI","TU","I","TE"],
               "1028":["HI","GA","SI","NO","MI","YA","KO","HA","HU","RU","KU",
                       "KA","RA"],
               "1029":["O","U","KO","KU","TO","KO","U","RI","yu","U","GA",
                       "A","RI",],
               "1030":["DO","KU","JI","NO","BU","NN","KA","WO","MO","TU"],
               "1031":["TO","KU","HI","TU","SU","BE","KI","HA","HU","RO","U",
                       "HU","SI","NO"],
               "1032":["KE","NN","KI","yu","U","DE",],
               "1033":["HE","I","KI","NN","JI","yu","MI","yo","U","GA",
                       "TA","KA","I"],
               "1034":["TO","KU","TI","yo","U","TE","KI","NA","KA","ME","NN",
                       "GA"],
               "1035":["TO","KU","SA","NN","HI","NN","DE","A","RU"],
               "1036":["SI","NN","SE","I","TI","KU","NI","TU","I","TE"],
               "1037":["SI","NN","SE","I","TI","KU","HA","DA","I","SI","NN",
                       "KA","NN","WO",],
               "1038":["SE","KI","NI","NN","SI","ya","TO","SI","TE",","],
               "1039":["KA","KU","GI","SI","KI","NO","U","NN","E",
                       "I","NI","A","TA","RU"],
               "1040":["TO","KU","NI","TI","yu","U","O","U","SI","NN","DE",
                       "NN","NO"],
               "1041":["SI","NN","PI","BU","HA","KA","TA","KU","TO","ZA","SA",
                       "RE"],
               "1042":["BU","GA","I","SI","ya","NO","TA","TI","I","RI","HA",],
               "1043":["YU","RU","SA","RE","TE","I","NA","I"],
               "1044":[],
               "1045":["U","RO","BO","RO","SU","NI","TU","I","TE"],
               "1046":[],
               "1047":[],
               "1048":[],
               "1049":[],
               "1050":[],
               "1051":["PE","-","JI","GA","YA","BU","RA","RE","TE","I","RU",
                       ".",".","."],
               "1052":[],
               "1053":[],
               "2000":["GI","yo","KU","ZA","NI","SU","WA","RI","MA","SU",
                       "KA","?"],
               "2001":["E","NN","DE","i","NN","GU","I","TI",],
               "2002":["A","NA","TA","HA","GI","yo","KU","ZA","WO","TE","NI",
                       "I","RE","TA"],
               "2003":["KO","NN","KA","I","NO","O","U","GO","RO","SI","MO",
                       "KO","RE","DE",],
               "2004":["SI","yu","U","RI","yo","U","SI","TA"],
               "2005":["HA","TA","SI","TE","JI","KA","I","HA",],
               "2006":["DO","U","NA","RU","NO","DA","RO","U","KA",",",
                       ",",",","?"],
               "2010":["KE","tu","SI","yo","U","WO","KU",
                       "DA","KI","MA","SU","KA","?"],               
               "2011":["E","NN","DE","i","NN","GU","NI",],
               "2012":["A","NA","TA","HA","TO","KI","NO","NA","GA","RE","WO",],
               "2013":["HA","KA","I","SI","TA"],
               "2014":["KA","KO","MO","MI","RA","I","MO","NA","KU",",",
                       "KO","U","HU","KU","NA",],
               "2015":["I","MA","GA","E","I","E","NN","NI","TU","DU",
                       "KU",",",",",","],
               "2016":["MI","RA","I","NO","SU","BE","TE","NO","KA","NO","U",
                       "SE","I","TO",],
               "2017":["HI","KI","KA","E","NI",","],
               "2018":["A","NN","NE","I","NO","SE","KA","I","GA","O","TO",
                       "ZU","RE","TA"],               
               "3000":["MO","KU","TE","KI"],
               "3001":["O","U","KI","yu","U","NI","TA","DO","RI","TU","KU"],
               "3002":["HU","RU","I","MI","NA","TO","WO","MI","TU","KE","RU"],
               "3003":["HA","KU","GI","NN","NO","KI","SI","WO","TA","O","SU"],
               "3004":["MA","DO","U","I","NN","TI","yo","U",
                       "WO","TA","O","SU"],
               "3005":["MI","DO","RI","NO","KI","SI",
                       "WO","TA","O","SU"],               
               "3006":["O","U","GO","RO","SI","WO",
                       "NA","SI","TO","GE","RU"],                          
               
    }
    return txt

def text_get_s():
    txt = {

               "51":["I","RA","tu", "SI", "ya", "I", "MA", "SE"],
               "52":["SI","yo","U", "HI", "NN", "NO", "BA", "NN"],
               "53":["GO","U","WO", "E", "RA", "NN", "DE", "KU"],
               "54":["DA","SA","I"],
               "55":["E","I","HE", "I", "NO", "ME", "MO", "GA"],
               "56":["KI"],
               "57":["KA","I","MA","SU","KA","?"],
               "58":["O","U","KI", "yu", "U", "KA", "RA", "NO"],
               "59":["TE","GA","MI",],
               "60":["KA","I","MA","SU","KA","?"],
               "61":["DA","I","SI", "yo", "KO", "NO", "KA", "GI"],
               "62":["KA","I","MA","SU","KA","?"],
               "63":["SA","BI","TA", "O", "O", "KI", "NA", "KA"],
               "64":["GI"],
               "65":["KA","I","MA","SU","KA","?"],
               "66":["U","RI","KI", "RE", "DE", "SU",],
               "67":["O","KA","NE", "GA", "TA", "RI", "MA", "SE"],
               "68":["NN"],
               "69":["MA","I","DO", "A", "RI",],

    }
    return txt

def text_get_s2():
    txt = {

               "51":["I","RA","tu", "SI", "ya", "I", "MA", "SE"],
               "52":["SI","yo","U", "HI", "NN", "NO", "BA", "NN"],
               "53":["GO","U","WO", "E", "RA", "NN", "DE", "KU"],
               "54":["DA","SA","I"],
               "55":["GU","NN","RE", "I", "JI", "yo", "U"],
               "56":[],
               "57":["KA","I","MA","SU","KA","?"],
               "58":["SO","NN","TI", "yo", "U", "NO", "ME", "MO"],
               "59":["GA","MI",],
               "60":["KA","I","MA","SU","KA","?"],
               "61":["JI","NN","TI", "NO", "KA", "GI"],
               "62":["KA","I","MA","SU","KA","?"],
               "63":["SI","NN","E", "I", "TA", "I", "NO",],
               "64":["WA", "NN", "SI", "yo" ,"U"],
               "65":["KA","I","MA","SU","KA","?"],
               "66":["U","RI","KI", "RE", "DE", "SU",],
               "67":["O","KA","NE", "GA", "TA", "RI", "MA", "SE"],
               "68":["NN"],
               "69":["MA","I","DO", "A", "RI",],

    }
    return txt

def text_get_s3():
    txt = {

               "51":["I","RA","tu", "SI", "ya", "I", "MA", "SE"],
               "52":["SI","yo","U", "HI", "NN", "NO", "BA", "NN"],
               "53":["GO","U","WO", "E", "RA", "NN", "DE", "KU"],
               "54":["DA","SA","I"],
               "55":["KO","U","JI", "KI", "RO", "KU",],
               "56":[],
               "57":["KA","I","MA","SU","KA","?"],
               "58":["KE","NN","KI", "yu", "U", "I", "NN", "NO"],
               "59":["ME","MO",],
               "60":["KA","I","MA","SU","KA","?"],
               "61":["A","KA","I", "KA", "-", "DO", "KI", "-"],
               "62":["KA","I","MA","SU","KA","?"],
               "63":["MI","DO","RI", "NO","KA","-","DO","KI","-"],
               "64":[],
               "65":["KA","I","MA","SU","KA","?"],
               "66":["U","RI","KI", "RE", "DE", "SU",],
               "67":["O","KA","NE", "GA", "TA", "RI", "MA", "SE"],
               "68":["NN"],
               "69":["MA","I","DO", "A", "RI",],
    }
    return txt

def text_get_s4():
    txt = {

               "51":["I","RA","tu", "SI", "ya", "I", "MA", "SE"],
               "52":["SI","yo","U", "HI", "NN", "NO", "BA", "NN"],
               "53":["GO","U","WO", "E", "RA", "NN", "DE", "KU"],
               "54":["DA","SA","I"],
               "55":["A","SI","GA", "RU", "NO", "ME", "MO", "GA"],
               "56":["KI"],
               "57":["KA","I","MA","SU","KA","?"],
               "58":["HU","RU","BI", "TA", "MA", "KI", "MO", "NO"],
               "59":[],
               "60":["KA","I","MA","SU","KA","?"],
               "61":["O","NI", "NO", "KA", "ME", "NN"],
               "62":["KA","I","MA","SU","KA","?"],
               "63":["O","NN","NA", "NO", "KA", "ME", "NN",],
               "64":[],
               "65":["KA","I","MA","SU","KA","?"],
               "66":["U","RI","KI", "RE", "DE", "SU",],
               "67":["O","KA","NE", "GA", "TA", "RI", "MA", "SE"],
               "68":["NN"],
               "69":["MA","I","DO", "A", "RI",],
    }
    return txt

def text_get_s5():
    txt = {

               "51":["I","RA","tu", "SI", "ya", "I", "MA", "SE"],
               "52":["SI","yo","U", "HI", "NN", "NO", "BA", "NN"],
               "53":["GO","U","WO", "E", "RA", "NN", "DE", "KU"],
               "54":["DA","SA","I"],
               "55":["E","I","HE", "I", "NO", "ME", "MO", "GA"],
               "56":["KI"],
               "57":["KA","I","MA","SU","KA","?"],
               "58":["O","U","KI", "yu", "U", "KA", "RA", "NO"],
               "59":["TE","GA","MI",],
               "60":["KA","I","MA","SU","KA","?"],
               "61":["DA","I","SI", "yo", "KO", "NO", "KA", "GI"],
               "62":["KA","I","MA","SU","KA","?"],
               "63":["SA","BI","TA", "O", "O", "KI", "NA", "KA"],
               "64":["GI"],
               "65":["KA","I","MA","SU","KA","?"],
               "66":["U","RI","KI", "RE", "DE", "SU",],
               "67":["O","KA","NE", "GA", "TA", "RI", "MA", "SE"],
               "68":["NN"],
               "69":["MA","I","DO", "A", "RI",],
    }
    return txt

def text_get_s6():
    txt = {

               "51":["I","RA","tu", "SI", "ya", "I", "MA", "SE"],
               "52":["SI","yo","U", "HI", "NN", "NO", "BA", "NN"],
               "53":["GO","U","WO", "E", "RA", "NN", "DE", "KU"],
               "54":["DA","SA","I"],
               "55":["E","I","HE", "I", "NO", "ME", "MO", "GA"],
               "56":["KI"],
               "57":["KA","I","MA","SU","KA","?"],
               "58":["O","U","KI", "yu", "U", "KA", "RA", "NO"],
               "59":["TE","GA","MI",],
               "60":["KA","I","MA","SU","KA","?"],
               "61":["DA","I","SI", "yo", "KO", "NO", "KA", "GI"],
               "62":["KA","I","MA","SU","KA","?"],
               "63":["SA","BI","TA", "O", "O", "KI", "NA", "KA"],
               "64":["GI"],
               "65":["KA","I","MA","SU","KA","?"],
               "66":["U","RI","KI", "RE", "DE", "SU",],
               "67":["O","KA","NE", "GA", "TA", "RI", "MA", "SE"],
               "68":["NN"],
               "69":["MA","I","DO", "A", "RI",],
    }
    return txt               
               
def item_get():
    txt = {

               "0":["U","RI","KI","RE"],
               "1":["JI","yo","U","HO","U","I","TI"],
               "2":["JI","yo","U","HO","U","NI"],
               "3":["KA","GI","I","TI"],
               "4":["KA","GI","NI"],
               "5":["TA","I","MA","TU",],
               "6":["KI","TI","yo","U","HI","NN","I","TI",],
               "7":["KA","GI","SA","NN"],
               "8":["JI","yo","U","HO","U","SA","NN",],

    }
    return txt

def item_get2():
    txt = {

               "0":["U","RI","KI","RE"],
               "1":["JI","yo","U","HO","U","YO","NN"],
               "2":["JI","yo","U","HO","U","GO",],
               "3":["KA","GI","GO",],
               "4":["WA","NN","SI","yo","U"],
               "5":["BA","KU","YA","KU",],
               "6":["KI","TI","yo","U","HI","NN","NI"],
               "7":["KA","GI","RO","KU",],
               "8":["JI","yo","U","HO","U","RO","KU"],

    }
    return txt

def item_get3():
    txt = {

               "0":["U","RI","KI","RE"],
               "1":["JI","yo","U","HO","U","NA","NA"],
               "2":["JI","yo","U","HO","U","HA","TI"],
               "3":["KA","-","DO","KI","-","I","TI"],
               "4":["KA","-","DO","KI","-","NI",],
               "5":["MA","RI","yo","KU","RA","NN","TA","NN"],
               "6":["KI","TI","yo","U","HI","NN","SA","NN"],
               "7":["KA","-","DO","KI","-","SA","NN"],
               "8":["JI","yo","U","HO","U","KI","yu","U"],

    }
    return txt

def item_get4():
    txt = {

               "0":["U","RI","KI","RE"],
               "1":["JI","yo","U","HO","U","JI","yu","U"],
               "2":["MA","KI","MO","NO",],
               "3":["KA","ME","NN","I","TI",],
               "4":["KA","ME","NN","NI",],
               "5":["GA","NN","YA","KU",],
               "6":["KI","TI","yo","U","HI","NN","YO","NN"],
               "7":["KA","ME","NN","SA","NN",],
               "8":["JI","yo","U","HO","U","JI","yu","U","I","TI"],

    }
    return txt

def item_get5():
    txt = {

               "0":["U","RI","KI","RE"],
               "1":["KA","GI","YO","NN"],
               "2":["KA","GI","NA","NA"],
               "3":["KA","GI","HA","TI"],
               "4":["KA","GI","KI","yu","U"],
               "5":["KA","I","ZU","I","TI"],
               "6":["KA","I","ZU","NI",],
               "7":["KA","I","ZU","SA","NN"],
               "8":["KA","I","ZU","YO","NN"],

    }
    return txt

def item_get6():
    txt = {

               "0":["U","RI","KI","RE"],
               "1":["O","U","NO","KA","GI",],
               "2":["SA","KU","SE","I","TI","yu","U"],
               "3":["SA","KU","SE","I","TI","yu","U"],
               "4":["SA","KU","SE","I","TI","yu","U"],
               "5":["SA","KU","SE","I","TI","yu","U"],
               "6":["SA","KU","SE","I","TI","yu","U"],
               "7":["SA","KU","SE","I","TI","yu","U"],
               "8":["SA","KU","SE","I","TI","yu","U"],

    }
    return txt

def item_get_t():
    txt = {
               "1":[["E","I","HE","I","NO","ME","MO","GA","KI"],
                    ["O","U","KI","yu","U","NO","HI","JI","yo","U","TU"],
                    ["U","RO","NO","TE","NN","KE","NN","GA","A","tu","TA"],
                    ["DA","I","SI","yo","KO","NO","SO","U","TI","HA","SA"],
                    ["I","TE","NN","KE","NN","GA","HI","TU","YO","U"],],
               "2":[["O","U","KI","yu","U","KA","RA","NO","TE","GA","MI"],
                    ["MI","NA","TO","HA","SI","BA","RA","KU","HE","I","SA"],
                    ["SU","RU",],
                    ["KI","NN","KI","yu","U","JI","NI","HA","KI","yu","U"],
                    ["SI","GA","I","NO","DA","I","NI","TI","KU","WO","TU"],
                    ["KA","U","KO","TO",]],
               "3":[["DA","I","SI", "yo", "KO", "NO", "KA", "GI"],
                    ["MI","YA","KO","NO","HA","ZU","RE","NI","A","RU","DA"],
                    ["I","SI","yo","KO","NO","KA","GI",]],
               "4":[["SA","BI","TA", "O", "O", "KI", "NA", "KA","GI"],
                    ["TO","KU","SI","yu","NA","TU","KU","RI","NO","O","O"],
                    ["KI","NA","KA","GI"]],
               "5":[["TA","I","MA","TU"],
                    ["KU","RA","YA","MI","WO","TE","RA","SI","TA","RI"],
                    ["KU","SA","KI","WO","YA","KI","HA","RA","U","NO","NI"],
                    ["TU","KA","U"],],
               "6":[["HU","RU","BI","TA","ME","DA","RU"],
                    ["SA","BI","DE","YO","GO","RE","TA","ME","DA","RU",],
                    ["O","U","KE","NO","MO","NN","SI","yo","U","GA",],
                    ["HO","RA","RE","TE","I","RU",]],
               "7":[["KA","NN","SI", "yu", "NO", "KA", "GI"],
                    ["MI","YA","KO","NO","TI","KA","RO","U","NO","KA","NN"],
                    ["SI","yu","NO","KA","GI",]],
               "8":[["KI","SI","NO", "ME", "MO", "GA","KI"],
                    ["O","U","GO","RO","SI","GA","HA","JI","MA","tu","TA"],
                    ["NO","DE","HE","I","KA","HA","KE","I","SI","yo","U","NO"],
                    ["SA", "I","DA","NN","HE","TO","MU","KA","WA","RE","TA"],
                    ["WA","TA","SI","MO","MI","NO","HU","RI","KA","TA","WO"],
                    ["KA","NN","GA","NE","BA","NA","RA","NA","I",".",".","."]],

    }
    return txt

def item_get_t2():
    txt = {
               "1":[["GU","NN","RE", "I", "JI", "yo", "U"],
                    ["KI","TA","NO","KO","U","DO","U","NO","TI","yo","U","SA"],
                    ["GA","O","WA","RU","MA","DE","MU","RA","HA",],
                    ["KI","SI","DA","NN","NO","SI","KI","KA","TO","SU","RU"],
                    ["SI","JI","NI","SI","TA","GA","U","KO","TO"],],
               "2":[["SO","NN","TI", "yo", "U", "NO", "ME", "MO","GA","KI"],
                    ["MI","YA","KO","KA","RA","SI","SI","ya","GA","KI","TA"],
                    ["MU","RA","NO","HI","MI","TU","WO","MA","MO","RU","KO",],
                    ["NO","YA","KU","ME","KA","RA","MO","YA","tu","TO",],
                    ["KA","I","HO","U","SA","RE","RU",],
                    ["WA","SI","HA","TE","WO","YO","GO","SI","SU","GI","TA"]],
               "3":[["JI","NN","TI", "NO", "KA", "GI"],
                    ["MU","RA","NI","SE","TU","E","I","SA","RE","TA",],
                    ["JI","NN","TI","NO","KA","GI",]],
               "4":[["WA", "NN", "SI", "yo" ,"U"],
                    ["JI","NN","TI","NO","SI","NN","E","I","TA","I","NO"],
                    ["WA", "NN", "SI", "yo" ,"U"]],
               "5":[["BA","KU","YA","KU"],
                    ["GA","NN","BA","NN","WO","HA","KA","I","SU","RU"],
                    ["KO","TO","GA","DE","KI","RU","KI","yo","U","RI","yo"],
                    ["KU","NA","KA","YA","KU"],],
               "6":[["SU","I","SI","yo","U","DA","MA"],
                    ["MU","RA","NO","KI","TA","NO","KO","U","DO","U",],
                    ["DE","MI","TU","KE","TA","SU","I","SI","yo","U",],
                    ["KU","RO","I","HE","BI","NO","YO","U","NA","MO","NO"],
                    ["GA","NA","KA","NI","MI","E","RU",]],
               "7":[["SI","NN","PI", "BU", "NO", "KA", "GI"],
                    ["SI","NN","SE","I","TI","KU","NO","SI","NN","PI","BU"],
                    ["NO","KA","GI",]],
               "8":[["KI","SI","NO", "ME", "MO", "GA","KI"],
                    ["HE","I","KA","NO","NA","SA","RU","KO","TO","NI",],
                    ["ZE","NN","ME","NN","TE","KI","NI","DO","U","I","HA",],
                    ["DE", "KI","NA","I","GA",".",".",".",],
                    ["KO","RE","DE","SU","BE","TE","GA","KA","I","KE","TU"],
                    ["SU","RU","NA","RA","YA","MU","WO","E","MA","I",]],

    }
    return txt

def item_get_t3():
    txt = {
               "1":[["MA","DO","U","I","NN","KO","U","JI","KI","RO","KU"],
                    ["RO","KU","GA","TU","HU","TU","KA",],
                    ["SA","I","SI","NN","BU","NO","HO","KA","NN","KO","NO",],
                    ["TE","SU","TO","WO","O","KO","NA","tu","TA",],
                    ["I","JI","yo","U","NA","SI",],],
               "2":[["KE","NN","KI","yu","U","I","NN","NO","ME","MO",],
                    ["SE","I","TI","yo","U","NO","TE","SI","SI",],
                    ["JI","KA","NN","NO","NA","GA","RE","NO","DO","NN","KA"],
                    ["TE","KI","SE","TU","NA","BA","I","TA","I","NO",],
                    ["SE","NN","TE","I","WO","I","SO","GU",],
                    ["JI","KA","I","NO","NI","tu","SI","yo","KU","WO"],
                    ["KE","I","SA","NN","SI","TE","O","KU","KO","TO"]],
               "3":[["A","KA","I","KA","-","DO","KI","-",],
                    ["MA","DO","U","I","NN","NO","MO","NN","SI","yo","U","GA"],
                    ["HA","I","tu","TA","KA","-","DO","KI","-",]],
               "4":[["MI","DO","RI","NO","KA","-","DO","KI","-",],
                    ["MA","DO","U","I","NN","NO","MO","NN","SI","yo","U","GA"],
                    ["HA","I","tu","TA","KA","-","DO","KI","-",]],
               "5":[["MA","RI","yo","KU","RA","NN","TA","NN"],
                    ["MA","DO","U","I","NN","DE","SI","SA","KU",],
                    ["SA","RE","TA","MA","RI","yo","KU","WO",],
                    ["DO","U","RI","yo","KU","TO","SU","RU",],
                    ["RA","NN","TA","NN"]],
               "6":[["NA","ZO","NO","DA","I","ZA",],
                    ["MA","DO","U","I","NN","SA","I","SI","NN","BU","NI"],
                    ["HO","KA","NN","SA","RE","TE","I","TA","NA","ZO","NO"],
                    ["KI","NN","ZO","KU","SE","I","NO","DA","I","ZA"]],
               "7":[["MU","RA","SA","KI","NO","KA","-","DO","KI","-",],
                    ["MA","DO","U","I","NN","NO","MO","NN","SI","yo","U","GA"],
                    ["HA","I","tu","TA","KA","-","DO","KI","-",],
                    ["SA","I","JI","yu","U","YO","U","E","RI","A","NI",],
                    ["HA","I","RU","TA","ME","NI","TU","KA","U"]],
               "8":[["I","NN","TI","yo","U","NO", "ME", "MO", "GA","KI"],
                    ["KA","SE","TU","GA","TA","DA","SI","KE","RE","BA",],
                    ["JI","KA","I","NO","NI","tu","SI","yo","KU","GA",],
                    ["SA", "I","GO","NO","O","U","GO","RO","SI","DA"],
                    ["SU","BE","TE","HA","SE","KA","I","NO","TO","WA","NO"],
                    ["HE","I","O","NN","NO","TA","ME","NI",".",".","."]],

    }
    return txt

def item_get_t4():
    txt = {
               "1":[["A","SI","GA","RU","NO","ME","MO","GA","KI"],
                    ["SO","U","KO","NO","SI","yu","U","RI","GA",],
                    ["O","WA","RU","MA","DE","HA","KE","I","BI","WO",],
                    ["KI","yo","U","KA","SU","RU","KO","TO",],
                    ["TO","U","ZO","KU","NI","TI","yu","U","I",],],
               "2":[["HU","RU","BI","TA","MA","KI","MO","NO",],
                    ["TA","I","KI","yo","KU","DE","NN","HA",],
                    ["GA","I","BU","TO","SI","ya","DA","NN","SA","RE","TE"],
                    ["I","NA","KE","RE","BA","NA","RA","NA","I"],
                    ["DE","NN","TO","U","TE","KI","NI","HA","KA","WA","NO",],
                    ["MI","ZU","WO","HI","KU","KO","TO","DE","KO","RE","WO"],
                    ["JI","TU","GE","NN","SU","RU"],
                    ],
               "3":[["O","NI", "NO", "KA", "ME", "NN"],
                    ["HI","GA","SI","NO","MI","YA","KO","TO","KU","YU","U",
                     "NO"],
                    ["O","NI","NO","KA","ME","NN",],
                    ["SI","KA","SI","HI","TO","GA","KA","BU","RU","TA","ME"],
                    ["NI","HA","TU","KU","RA","RE","TE","O","RA","ZU"],
                    ["HA","I","BU","NI","NA","ZO","NO","KU","BO","MI","GA",
                     "A","RU"]],
               "4":[["O","NN","NA", "NO", "KA", "ME", "NN",],
                    ["HI","GA","SI","NO","MI","YA","KO","TO","KU","YU","U",
                     "NO"],
                    ["O","NN","NA","NO","KA","ME","NN",],
                    ["SI","KA","SI","HI","TO","GA","KA","BU","RU","TA","ME"],
                    ["NI","HA","TU","KU","RA","RE","TE","O","RA","ZU"],
                    ["HA","I","BU","NI","NA","ZO","NO","KU","BO","MI","GA",
                     "A","RU"]],
               "5":[["GA","NN","YA","KU"],
                    ["HI","GA","SI","NO","MI","YA","KO","DE","TU","KU","RA",
                     "RE","TA"],
                    ["GA","NN","YA","KU",],
                    ["JI","KA","NN","KE","I","KA","TO","TO","MO","NI",],
                    ["TA","I","RI","yo","KU","GA",],
                    ["KA","I","HU","KU","SU","RU"]],
               "6":[["NA","ZO","NO","HA","KO",],
                    ["TA","I","KI","yo","KU","DE","NN","SA","I","SI",
                     "NN","BU","DE"],
                    ["HO","KA","NN","SA","RE","TE","I","TA","KI","BA","KO"],
                    ["GO","HU","TO","KU","SA","RI","DE",],
                    ["GE","NN","JI","yu","U","NI"],
                    ["HU","U","GA","SA","RE","TE","I","RU"]],
               "7":[["RO","U","JI", "NN", "NO", "KA", "ME", "NN"],
                    ["HI","GA","SI","NO","MI","YA","KO","TO","KU","YU","U",
                     "NO"],
                    ["RO","U","JI","NN","NO","KA","ME","NN",],
                    ["SI","KA","SI","HI","TO","GA","KA","BU","RU","TA","ME"],
                    ["NI","HA","TU","KU","RA","RE","TE","O","RA","ZU"],
                    ["HA","I","BU","NI","NA","ZO","NO","KU","BO","MI","GA",
                     "A","RU"]],
               "8":[["GA","I","KO", "U", "BU", "NN","SI", "yo"],
                    ["KI","KO","KU","TO","TO","U","HO","U","DE",],
                    ["KU","DA","NN","NO","I","BU","TU","NI","TU","I",
                     "TE","HA"],
                    ["BU", "NN","KA","TU","SI","TE","HO","KA","NN",],
                    ["SU","RU","KO","TO","NI","DO","U","I","SU","RU",],
                    ["KU","RE","GU","RE","MO","SI","NN","TI","yo","U","NI",],
                    ["TO","RI","A","TU","KA","WA","RE","TA","SI"]],

    }
    return txt

def item_get_t5():
    txt = {
               "1":[["KI","SI","DA","NN","TI","yo","U","NO","KA","GI"],
                    ["KA","RE","GA","KI","SI","DA","NN","TI","yo","U","NI"],
                    ["NI","NN","JI","RA","RE","TA","TO","KI","NI",],
                    ["O","U","KA","RA","SA","ZU","KE","RA","RE","TA",],
                    ["KA","GI",]],
               "2":[["HA","KU","GI","NN","NO","KI","SI","NO","KA","GI"],
                    ["O","U","NI","TU","KA","E","TA",],
                    ["HA","KU","GI","NN","NO","KI","SI","HA"],
                    ["MO","TO","HA","DA","I","SI","NN","KA","NN","NO",],
                    ["GO","E","I","HE","I","DA","tu","TA",],],
               "3":[["MA","DO","U", "I", "NN", "TI","yo","U","NO", "KA", "GI"],
                    ["KA","RE","GA","TO","KI","NO","KE","NN","KI","yu","U"],
                    ["JI","yo","NO","SI","yo","TI","yo","U","NI"],
                    ["NI","NN","JI","RA","RE","TA","TO","KI","NI",],
                    ["O","U","KA","RA","SA","ZU","KE","RA","RE","TA",],
                    ["KA","GI",]],
               "4":[["MI","DO","RI", "NO", "KI", "SI", "NO", "KA","GI"],
                    ["O","U","NO","SO","tu","KI","NN","NO","MI","DO","RI"],
                    ["NO","KI","SI","HA","HI","GA","SI","NO","MI","YA","KO"],
                    ["NO","SI","yu","tu","SI","NN","DE"],
                    ["KE","NN","JI","yu","TU","NI","TA","KE","TE","I","TA"]],
               "5":[["HU","RU","BI","TA","KA","I","ZU",],
                    ["HE","NN","KI","yo","U","NO","MU","RA","HE","NO"],
                    ["KO","U","RO","GA","KA","I","TE","A","RU",]],
               "6":[["MA","A","TA","RA","SI","I","KA","I","ZU",],
                    ["O","U","RI","TU","MA","DO","U","I","NN","HE","NO"],
                    ["KO","U","RO","GA","KA","I","TE","A","RU",]],
               "7":[["SU","NA","BO","KO","RI","NO","KA","I","ZU",],
                    ["HI","GA","SI","NO","MI","YA","KO","HE","NO"],
                    ["KO","U","RO","GA","KA","I","TE","A","RU",]],
               "8":[["O","U","KE","NO","KA","I","ZU",],
                    ["KE","I","SI","yo","U","NO","SA","I","DA","NN","HE","NO"],
                    ["KO","U","RO","GA","KA","I","TE","A","RU",]],

    }
    return txt

def item_get_t6():
    txt = {
               "1":[["O","U","NO","KA","GI",],
                    ["KO","KU","O","U","GA","MO","tu","TE","I","TA","KA","GI"],
                    [],
                    [],
                    ["DO","KO","NO","TO","BI","RA","NI",],
                    ["TA","I","O","U","SI","TE","I","RU","NO","DA","RO","U",
                     "?"],],
               "2":[["O","U","KI","yu","U","KA","RA","NO","TE","GA","MI"],
                    ["MI","NA","TO","HA","SI","BA","RA","KU","HE","I","SA"],
                    ["SU","RU",],
                    ["KI","NN","KI","yu","U","JI","NI","HA","KI","yu","U"],
                    ["SI","GA","I","NO","DA","I","NI","TI","KU","WO","TU"],
                    ["KA","U","KO","TO",]],
               "3":[["DA","I","SI", "yo", "KO", "NO", "KA", "GI"],
                    ["MI","YA","KO","NO","HA","ZU","RE","NI","A","RU","DA"],
                    ["I","SI","yo","KO","NO","KA","GI",]],
               "4":[["SA","BI","TA", "O", "O", "KI", "NA", "KA","GI"],
                    ["TO","KU","SI","yu","NA","TU","KU","RI","NO","O","O"],
                    ["KI","NA","KA","GI"]],
               "5":[["KA","I","ZU","I","IT"],
                    ["HE","NN","KI","yo","U","NO","MU","RA","HE","NO"],
                    ["KO","U","RO","GA","KA","I","TE","A","RU",]],
               "6":[["HU","RU","BI","TA","ME","DA","RU"],
                    ["SA","BI","DE","YO","GO","RE","TA","ME","DA","RU",],
                    ["O","U","KE","NO","MO","NN","SI","yo","U","GA",],
                    ["HO","RA","RE","TE","I","RU",]],
               "7":[["KA","NN","SI", "yu", "NO", "KA", "GI"],
                    ["MI","YA","KO","NO","TI","KA","RO","U","NO","KA","NN"],
                    ["SI","yu","NO","KA","GI",]],
               "8":[["KI","SI","NO", "ME", "MO", "GA","KI"],
                    ["O","U","GO","RO","SI","GA","HA","JI","MA","tu","TA"],
                    ["NO","DE","HE","I","KA","HA","KE","I","SI","yo","U","NO"],
                    ["SA", "I","DA","NN","HE","TO","MU","KA","WA","RE","TA"],
                    ["WA","TA","SI","MO","MI","NO","HU","RI","KA","TA","WO"],
                    ["KA","NN","GA","NE","BA","NA","RA","NA","I",".",".","."]],

    }
    return txt