# -*- coding: utf-8 -*-
#Game_status
def costs_get():
    c = {
               "0":100,
               "1":100,
               "2":100,
               "5":50,
               "17":500,
               "18":500,
               "19":500,
               "20":500,
               "21":500,
               "22":500,
               "32":100,
               "33":100,
               "34":100,
               "64":100,
               "65":100,
               "66":100,
               "80":200,
               "1271":50,
               "1272":50,
               "133":500,
               "1331":500,
               "140":1000,
               "141":3000,
               "142":1000,
               "143":3000,
               "150":100,
               "151":1500,
               "152":1500,
               "153":3000,
               "171":1000,
               "172":1000,
               "173":1000,
               "500":100,
               "600":500,
               "1000":1000,
    }
    return c

def oda(l):
    if l == "ja":
        d = {
               "kome":2000,
               "sikin":1000,
               "heisi":1000,
               "sei":["O","DA"],
               "mei":["NO","BU","NA","GA"],
               "msg":{"0-1":["SU","MA","NA","I","GA",],
                      "0-2":["I","KU","SA","NI","MU","KE","TE"],
                      "0-3":["I","I","KA","GE","NN","NI",],
                      "1-1":["HI","yo","U","RO","U","NO",],
                      "1-2":["SI","KI","NN","NO",],
                      "1-3":["HE","I","SI","NO",],
                      "2":["TE","I","KI","yo","U","WO"],
                      "3-1":["O","NE","GA","I","SI","TA","I"],
                      "3-2":["TA","NO","MI","TA","I"],
                      "3-3":["SE","YO",],
                      "4":["KA","NN","SI","ya","SU","RU"],
                      "5":["SO","U","KA",".",".","."],
                      "6":["MU","RI","JI","I","HA"],
                      "7":["SU","MA","I",],
                      "10-1":["I","MA","GA","WA","TO","NO"],
                      "10-2":["I","KU","SA","DA",],
                      "10-3":["E","NN","GU","NN","WO","TA","NO","MU"],
                      "10-4":[],
                      "11-1":["I","MA","GA","WA","TO","NO"],
                      "11-2":["I","KU","SA","DA",],
                      "11-3":["SU","KE","DA","TI","WO","TA","NO","MU"],
                      "11-4":[],
                      "12-1":["I","MA","GA","WA","TO","NO"],
                      "12-2":["KE","tu","SE","NN","DA",],
                      "12-3":["KI","DE","NN","NO","TA","SU","KE","GA"],
                      "12-4":["HU","KA","KE","TU","DE","A","RU"],                      
                      }
        }
    elif l == "en":
        d = {
               "kome":2000,
               "sikin":1000,
               "heisi":1000,
               "sei":"Oda",
               "mei":"Nobunaga",
               "msg":{"0-1":"I'm sorry, but",
                      "0-2":"For the war,",
                      "0-3":"That's enough.",
                      "1-1":"I want food.",
                      "1-2":"I want money.",
                      "1-3":"I want soldiers.",
                      "2":"",
                      "3-1":"I need your help.",
                      "3-2":"Please consider.",
                      "3-3":".......",
                      "4":"Thank you.",
                      "5":"I see....,",
                      "6":"I don't force.",
                      "7":"",
                      "10-1":"A battle with ",
                      "10-2":"Imagawa occurred.",
                      "10-3":"I request",
                      "10-4":"reinforcements.",
                      "11-1":"I Need ",
                      "11-2":"reinforcements",
                      "11-3":"for the battle",
                      "11-4":"with Imagawa. ",
                      "12-1":"It’s a decisive ",
                      "12-2":"battles with ",
                      "12-3":"Imagawa!",
                      "12-4":"Need your help!",                                            
                      }
        }
    return d

def imagawa(l):
    if l == "ja":
        d = {
               "kome":5000,
               "sikin":3000,
               "heisi":2000,
               "sei":["I","MA","GA","WA"],
               "mei":["YO","SI","MO","TO"],
               "msg":{"0-1":["SU","MA","NA","I","GA",],
                      "0-2":["I","KU","SA","NI","SO","NA","E","TE"],
                      "0-3":["SO","RO","SO","RO",],
                      "1-1":["HI","yo","U","RO","U","NO",],
                      "1-2":["SI","KI","NN","NO",],
                      "1-3":["HE","I","SI","NO",],
                      "2":["TE","I","KI","yo","U","WO"],
                      "3-1":["O","NE","GA","I","SU","RU",],
                      "3-2":["TA","NO","MI","TA","I"],
                      "3-3":["SU","RU","NO","DA","!",],
                      "4":["KA","TA","JI","KE","NA","I"],
                      "5":["HU","MU",".",".","."],
                      "6":["MA","A","SO","RE","MO"],
                      "7":["I","I","DA","RO","U",".",".","."],
                      "10-1":["O","DA","TO","NO"],
                      "10-2":["I","KU","SA","DA",],
                      "10-3":["E","NN","GU","NN","WO",],
                      "10-4":["YO","U","SE","I","SU","RU"],
                      "11-1":["O","DA","TO","NO"],
                      "11-2":["I","KU","SA","DA",],
                      "11-3":["GE","KI","SE","NN","TO","NA","RU"],
                      "11-4":["E","NN","GU","NN","WO","TA","NO","MU"],
                      "12-1":["O","DA","TO","NO"],
                      "12-2":["KE","tu","SE","NN","DA",],
                      "12-3":["TA","I","GU","NN","DE","KA","SE","I",],
                      "12-4":["SI","TE","HO","SI","I","!",],                                            
                      }
        }
    elif l == "en":
        d = {
               "kome":5000,
               "sikin":3000,
               "heisi":2000,
               "sei":"Imagawa",
               "mei":"Yoshimoto",
               "msg":{"0-1":"I'm sorry, but",
                      "0-2":"For the war,",
                      "0-3":"That's enough.",
                      "1-1":"I want food.",
                      "1-2":"I want money.",
                      "1-3":"I want soldiers.",
                      "2":"",
                      "3-1":"I need your help.",
                      "3-2":"Please consider.",
                      "3-3":".......",
                      "4":"Thank you.",
                      "5":"I see....,",
                      "6":"I don't force.",
                      "7":"",
                      "10-1":"A battle with ",
                      "10-2":"Oda occurred.",
                      "10-3":"I request",
                      "10-4":"reinforcements.",
                      "11-1":"Need reinforcements  ",
                      "11-2":"for the battle",
                      "11-3":"with Oda. ",
                      "11-4":"",
                      "12-1":"It’s a decisive ",
                      "12-2":"battles with ",
                      "12-3":"Oda!",
                      "12-4":"Need your help!",                     
                      }
        }        
    return d


