# -*- coding: utf-8 -*-
#Text_list_en.py

def text_get():
    txt = {
              
               "o1":"Better be the head of a pike ",
               "o2":"than the tail of a sturgeon.",
               "o3":"It is a saying that \"It is ",
               "o4":"better to be the head of ",
               "o5":"a small organization than",
               "o6":"to submit to a large",
               "o7":"organization.\"",
               "o8":"As a small lord between ",
               "o9":"Oda and Imagawa, you must",
               "o10":"survive without being ",
               "o11":"under anyone's control.",
               "o12":"",
               "o13":"Defeat either Oda or Imagawa!",
               "o14":"",
               "ox":"Next",
               "0":"Paddy field",
               "1":"Town",
               "2":"Samurai residence",
               "3":"Wood",
               "4":"River",
               "5":"Flat ground",
               "6":"Castle",
               "7":"Fence",
               "8":"Inside the castle",
               "9":"Bridge",
               "10":"Gate",
               "11":"Road",
               "12":"Road",
               "13":"Road",
               "14":"Road",
               "15":"Road",
               "16":"Road",
               "17":"Samurai leader",
               "18":"Diplomat",
               "19":"Ninja",
               "20":"Merchant",
               "21":"Nanban Merchant",
               "22":"Mercenary",
               "32":"Paddy field",
               "33":"Town",
               "34":"Samurai residence",
               "35":"Warehouse",
               "36":"Blacksmith",
               "37":"Dojo",
               "38":"Shrine",
               "39":"Temple",
               "40":"Church",               
               "64":"Paddy field",
               "65":"Town",
               "66":"Samurai residence",
               "67":"Embankment",
               "80":"Refurbishment",
               "93":"Defence",
               "94":"Offence",
               "95":"Soldiers",
               "96":"Money",
               "97":"Food",
               "98":"Cost",
               "99":"Can't build here.",
               "99_1":"No personnel available.",
               "100":"Build",
               "100_1":"Personnel",
               "100_2":"Command",
               "101":"Cancel",
               "102":"Execute",
               "103":"Save",
               "104":"Load",
               "105":"Next turn",
               "106":"turn",
               "107":"OK",
               "108":"Cost over",
               "109":"Save completed",
               "110":"Load completed",
               "111":"Load failed",
               "112":"Save failed",
               "113":"New game",
               "1131":"Load game",
               "114":"",
               "115":"is coming.",
               "116":"Agree",
               "117":"Disagree",
               "118":"Answer",
               "119":"is attacking.",
               "120":"Bandit army",
               "1201":"Oda army",
               "1202":"Imagawa army",
               "121":"You win!",
               "122":"You lose....",
               "123":"Draw",
               "124":"Next",
               "125":"You",
               "126":"Result report",
               "1271":"Attack training",
               "1272":"Defense training",
               "128":"Training completed.",
               "129":"Attack other forces",
               "130":"Attack other forces",
               "131":"",
               "132":"is the target.",
               "133":"Friendship to Oda",
               "1331":"Friendship to Imagawa",
               "134":"friendship has increased",
               "141":"Food(large)",
               "140":"Food(small)",
               "143":"Soldiers(large)",
               "142":"Soldiers(small)",
               "1400":"price",
               "1401":"You hired soldiers.",
               "1402":"You bought food.",
               "1403":"Not enough money",
               "150":"Spying",
               "151":"Sabotage to Oda",
               "152":"Sabotage to Imagawa",
               "153":"Dicord engineering",
               "157":"Friendship Oda-Imakawa",
               "158":"Completed sabotage.",
               "159":"Check the report.",
               "160":"Friendship",
               "161":"There was a battle ",
               "1612":"between Oda and Imakawa.",
               "170":"Where do you want to attack?",
               "171":"Oda",
               "172":"Imagawa",
               "173":"Bandits",
               "179":"You will attack on next turn.",
               "180":"Result",
               "181":"Return to title",
               "182":"Remaining",
               "183":"Total",
               "184":"Elapsed turn",
               "185":"Minus",
               "186":"Rank",
               "190":"There was heavy rain.",
               "191":"The river overflowed.",
               "200":"Surrender",
               "201":"Do you really Surrender?",
               "203":"Yes",
               "204":"No",
               "1000":"HINT",
               "1001":"Back",
               "1002":"About how to use Food.",
               "1003":"About how to use Money.",
               "1004":"About how to use Soldiers.",
               "1005":"About the battle.",
               "1006":"About the embankment.",
               "1012":["Food is needed to feed ",
                       "the soldiers.",
                       "Soldiers run away when food ",
                       "is scarce.",
                        "You can get more by increasing ",
                        "the number of Paddy fields.",],
               "1013":["Money is used for transactions",
                       "with merchants.",
                       "You can buy food and ",
                       "hire soldiers.",
                       "You can get more by increasing ",
                       "the number of towns."],
               "1014":["Soldiers fight during battles.",
                       "The more soldiers there are, ",
                       "the better the battle.",
                       "You can get more by increasing",
                       "the number of ",
                       "samurai residences."],
               "1015":["The number of soldiers is ",
                       "important in battle,",
                       "but training of soldiers must",
                       "not be neglected.",
                       "It is also important to",
                       "surrender when there is ",
                       "no chance of winning",
                       "or to diplomatically ",
                       "avoid a battle."],
               "1016":["The embankment prevents",
                       "the flooding of the river.",
                       "If there is a river ",
                       "in the territory,",
                       "you should prepare for",
                       "flooding.",
                       "The embankment can be built",
                       "on a flat land adjacent to",
                       "the river."],               
               
               

    }
    return txt

