# -*- coding: utf-8 -*-
#Text_list_en.py

def text_get():
    txt = {
              
               "o1":"Better be the head of a pike ",
               "o2":"than the tail of a sturgeon.",
               "o3":"It is a saying that \"It is ",
               "o4":"better to be the head of ",
               "o5":"a small organization than",
               "o6":"to submit to a large",
               "o7":"organization.\"",
               "o8":"As a small lord between ",
               "o9":"Oda and Imagawa, you must",
               "o10":"survive without being ",
               "o11":"under anyone's control.",
               "o12":"",
               "o13":"Defeat either Oda or Imagawa!",
               "o14":"",
               "ox":"Next",
               "0":"Paddy field",
               "1":"Town",
               "2":"Samurai residence",
               "3":"Wood",
               "4":"River",
               "5":"Flat ground",
               "6":"Castle",
               "7":"Fence",
               "8":"Inside the castle",
               "9":"Bridge",
               "10":"Gate",
               "11":"Road",
               "12":"Road",
               "13":"Road",
               "14":"Road",
               "15":"Road",
               "16":"Road",
               "17":"Samurai leader",
               "18":"Diplomat",
               "19":"Ninja",
               "20":"Merchant",
               "21":"Nanban Merchant",
               "22":"Mercenary",
               "32":"Paddy field",
               "33":"Town",
               "34":"Samurai residence",
               "35":"Warehouse",
               "36":"Blacksmith",
               "37":"Dojo",
               "38":"Shrine",
               "39":"Temple",
               "40":"Church",               
               "64":"Paddy field",
               "65":"Town",
               "66":"Samurai residence",
               "80":"Refurbishment",
               "93":"Defence",
               "94":"Offence",
               "95":"Soldiers",
               "96":"Money",
               "97":"Food",
               "98":"Cost",
               "99":"Can't build here.",
               "99_1":"No personnel available.",
               "100":"Build",
               "100_1":"Personnel",
               "100_2":"Command",
               "101":"Cancel",
               "102":"Execute",
               "103":"Save",
               "104":"Load",
               "105":"Next turn",
               "106":"turn",
               "107":"OK",
               "108":"Cost over",
               "109":"Save completed",
               "110":"Load completed",
               "111":"Load failed",
               "112":"Save failed",
               "113":"New game",
               "1131":"Load game",
               "114":"",
               "115":"is coming.",
               "116":"Agree",
               "117":"Disagree",
               "118":"Answer",
               "119":"is attacking.",
               "120":"Bandit army",
               "1201":"Oda army",
               "1202":"Imagawa army",
               "121":"You win!",
               "122":"You lose....",
               "123":"Draw",
               "124":"Next",
               "125":"You",
               "126":"Result report",
               "1271":"Attack training",
               "1272":"Defense training",
               "128":"Training completed.",
               "129":"Attack other forces",
               "130":"Attack other forces",
               "131":"",
               "132":"is the target.",
               "133":"Friendship to Oda",
               "1331":"Friendship to Imagawa",
               "134":"friendship has increased",
               "141":"Food(large)",
               "140":"Food(small)",
               "143":"Soldiers(large)",
               "142":"Soldiers(small)",
               "1400":"price",
               "1401":"You hired soldiers.",
               "1402":"You bought food.",
               "1403":"Not enough money",
               "150":"Spying",
               "151":"Sabotage to Oda",
               "152":"Sabotage to Imagawa",
               "153":"Dicord engineering",
               "157":"Friendship Oda-Imakawa",
               "158":"Completed sabotage.",
               "159":"Check the report.",
               "160":"Friendship",
               "161":"There was a battle ",
               "1612":"between Oda and Imakawa.",
               "170":"Where do you want to attack?",
               "171":"Oda",
               "172":"Imagawa",
               "173":"Bandits",
               "179":"You will attack on next turn.",
               "180":["HI","yo","U","KA",],
               "181":["TA","I","TO","RU","HE"],
               "182":["NO","KO","RI",],
               "183":["GO","U","KE","I"],
               "184":["KE","I","KA","TA","-","NN"],
               "185":["MA","I","NA","SU","BU","NN"],
               "186":["RA","NN","KU",],
               

    }
    return txt

